### ISSUE TITLE
Mock data

### ISSUE THREAD

**Issue by grgur** [RoboDomo/react-client#25]
Allow developers to use mock data so they don't have to run additional services

This would also help run regression tests on a CI service

MQTT messages could also be mocked in service workers. Example: https://googlechrome.github.io/samples/service-worker/mock-responses/service-worker.js

**Comment by mschwartz** [comment]
If a dev has some microservices, your want to be able to use those and mock the rest/others.

Some you may not want to mock at all.

You have to simulate MQTT, too, including retained messages.

**Comment by mschwartz** [comment]
How you specify what to mock can’t be in a config file, so maybe query_string or somehow env vars

**Comment by mschwartz** [comment]
The mock responses should be somewhat random in terms of latency

For example, if client sends "smartthings/set/switch on", then after some random delay, the status message comes in.

Simulate the cloud lag!

**Comment by grgur** [comment]
With #31 I went a slightly different way so I'm letting dev/qa users send arbitrary MQTT messages directly instead of mocking select or a configurable set of microservices. 

The implementation is slightly different than @mschwartz's comments, but it serves the purpose of testing and quick onboarding.
